<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SeddikClinic.Mobile.Shared</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SeddikClinic.Core\SeddikClinic.Core.csproj" />
  </ItemGroup>
</Project>
